### ISSUE TITLE
Capture OPAT outcomes in line with NORS guidance

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-opat#10]
We need at least one new field to for separate outcome measures.

Would also be great to include the NORS definitions inline if at all possible - perhaps in a wider modal.

**Comment by michaeledwardmarks** [comment]
As part of capturing the NORS outcome we should ask at the time of Outcome what the "Category" of the infection/problem was:

https://github.com/openhealthcare/elcid/issues/720

Sarah Logan said:
" It may be that the best way to record the outcomes is that we have to pick the category and then the outcomes are limited to those appropriate for that category."

**Comment by michaeledwardmarks** [comment]
This should be a two step process - 1 by the user and 1 automated.

In Line with NORS Appendix 1 Page 40.
- [ ]The user will enter the Primary Infective Diagnosis
- [ ] This will be done at the end of OPAT episode when recording outcomes
- [ ]elCID will in the background assign this to a category (e.g Bone and Joint Infection) for the purposes of summating diagnoses
- [ ] Both Entries will be outputed in the CSV

**Comment by michaeledwardmarks** [comment]
Closing and breaking out in to specific issues
