### ISSUE TITLE
As a Doctor I would like to see other clinical advice type records

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-opat#11]
Currently the OPAT team have no way to see advice / notes from other teams - e.g. Clinical Advice.

**Comment by davidmiller** [comment]
Fixed and deployed to http://david-staging.herokuapp.com/

**Comment by michaeledwardmarks** [comment]
How does this work?

**Comment by michaeledwardmarks** [comment]
e.g what are the steps that I should be trying out?

**Comment by davidmiller** [comment]
Create inpatient
Write some clinical advice
Create OPAT episode
Import data
Go to details view
See clinical advice

(Requested by Sarah in meeting w. @GabPoll )

**Comment by davidmiller** [comment]
This may be superseded by an OPAT notes view later on, but this is a half decent intermediary step!

**Comment by michaeledwardmarks** [comment]
This is a one off import I presume at present

**Comment by michaeledwardmarks** [comment]
Works

**Comment by GabPoll** [comment]
yep, good solution. Agree this is a short term fix as may be superseded by an integrated view similar to what is being developed for haem where CA and OPAT R/V all in one timeline.
