### ISSUE TITLE
Allergies Mandatory in OPAT

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#13]
https://github.com/openhealthcare/elcid/issues/183

Before updating/entering any antimicrobials for an OPAT episode, a user must either enter allergy information, or take an action to confirm that there are no known allergies.

**Comment by michaeledwardmarks** [comment]
- [x] When a patient moves from OPAT Referaal to OPAT Current we should check this

**Comment by davidmiller** [comment]
Deployed to david-staging

**Comment by michaeledwardmarks** [comment]
Fab
