### ISSUE TITLE
OPAT Referral should capture Referring Team and Consultant 

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#16]
https://github.com/openhealthcare/elcid/issues/589

Note also that Referring Team is suggested to change to a dropdown

**Comment by davidmiller** [comment]
There is currently no lookuplist for referring team - we'd need to create one!

**Comment by michaeledwardmarks** [comment]
We should probably use the list given in Appendix 1 of the NORS outcome booklet - Page 41

**Comment by davidmiller** [comment]
Use the NORS list
Keep Consultant

**Comment by michaeledwardmarks** [comment]
- [x] When a patient moves from OPAT Referral to OPAT Current we should check this

**Comment by davidmiller** [comment]
Deployed to david-staging

**Comment by michaeledwardmarks** [comment]
Nice.
You are able to move on without picking an option from the specialty drop down.
Is that deliberate?

**Comment by davidmiller** [comment]
In the first instance - we can always be stronger later!
