### ISSUE TITLE
Changes to Line Assessment Field

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#18]
Actions from this issue
- [x] Add a Dressing type lookuplist
- [ ] Give a null option to Dressing Intact
- [x] Add field "Date of next bionector"
- [x] Add field "Comments"
- [x] Make CM from exit a measurement in CM!

https://github.com/openhealthcare/elcid/issues/596

**Comment by davidmiller** [comment]
Apart from giving a null option, these are deployed to david-staging.

I guess we could convert to Yes/No/Null in the way that test results work, but it needs some thought to make sure we don't lose old yes data.

Propose to bump that aspect to 0.5!

**Comment by michaeledwardmarks** [comment]
Looks good.
Need to remember the Look-up list.
