### ISSUE TITLE
Change from Look-Up Lists to Drop-Downs for some fields

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#19]
- [x]  Line Type: Line Modal
- [x] Line Complications: Line Modal
- [x] Line Removal Reason: Line Modal
- [x] Frequency: Antimicrobial
- [x] Delivered By: Antimicrobial
- [x] Referring Team: Location

https://github.com/openhealthcare/elcid/issues/726

**Comment by davidmiller** [comment]
Suggest leaving referring team to be part of #16

**Comment by davidmiller** [comment]
Fixed and deployed to http://david-staging.herokuapp.com/

**Comment by michaeledwardmarks** [comment]
Fab.
We will make referring team a drop down too either in location or at the time of referral in line with #16 and using the NORS list
