### ISSUE TITLE
Record a Primary Infective Diagnosis in Line with NORS

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#20]
This should be a two step process - 1 by the user and 1 automated.

In Line with NORS Appendix 1 Page 40.
- [x] The user will enter the Primary Infective Diagnosis
- [x] This will be done at the end of OPAT episode when recording outcomes
- [ ] elCID will in the background assign this to a category (e.g Bone and Joint Infection) for the purposes of summating diagnoses
- [ ] Both Entries will be outputed in the CSV

**Comment by michaeledwardmarks** [comment]
- [x] Primary Infective Diagnosis should have it's own look-up distinct from other Diagnosis look-ups

**Comment by michaeledwardmarks** [comment]
- We capture this information at the time the patient finishes OPAT (e.g when we record OPAT Outcome Data #25 )

**Comment by davidmiller** [comment]
The bits of this for 0.4.3 are deployed to david-staging. 

I think that the remaining two should be a separate ticket.

**Comment by michaeledwardmarks** [comment]
Ok.
Closing and moving other 2 points to new issue.
