### ISSUE TITLE
NORS OPAT Adverse Events

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#24]
Antimicrobial Adverse Events captured in the Antimicrobial Modal
Line Adverse Events captured in the Line Modal

Change the drop-downs for these to the lists in NORS Appendix 1 page 42

For the CSV we need to capture the "total number of line and drug reactions"
So I suggest we give
- [ ]  a count of each drug adverse event across time period X
- [ ] Total of all drug adverse events across time period X
- [ ]  a count of each line adverse event across time period X
- [ ] Total of all line adverse events across time period X

**Comment by michaeledwardmarks** [comment]
Antimicrobial Modal
- [x] If Other Selected for Adverse Event - give free text box for details

Line Modal
- [x] If Other Selected for Complication - give free text box for details

**Comment by michaeledwardmarks** [comment]
Drop downs on davidstaging now match NORS

**Comment by davidmiller** [comment]
Deployed to david-staging

**Comment by michaeledwardmarks** [comment]
Great.
