### ISSUE TITLE
OPAT and Patient Outcome NORS category

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#25]
Change the way we capture these (currently captured when completing OPAT and then again when on OPAT-Review Ward Round).

We need to capture 
- [x] OPAT Outcome (three categories, NORS appendix 1 page 43)
- [x] Patient Outcome (4 categories, NORS appendix 1, page 43)

Then when we capture these we can subcategorise based on Primary Infective Diagnosis #20 Referring Team #16

**Comment by michaeledwardmarks** [comment]
- [x] End of IV (When patient leaves OPAT-Current) we capture both of these
- [x] OPAT-Review we re-capture the Patient-Outcome (not over-writing the original entry)

**Comment by davidmiller** [comment]
Deployed to david-staging

**Comment by michaeledwardmarks** [comment]
The data collection for this looks correct but note the issue in #12 that we are not capturing at the end of IV if the user selects "Ongoing OPAT Follow-Up".
