### ISSUE TITLE
Delivered by

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#26]
I think we should strongly consider changing to the NORS list of Delivered By

 Family/Carer
 Community Nurse (NHS)
 Community Nurse (non-NHS)
 General Practitioner
 OPAT Clinic
 Other (free text)
 Local hospital day unit

Pretty similar to what we have already, just some minor tweaks (Can be done in Admin by @michaeledwardmarks) once agreed with team

**Comment by michaeledwardmarks** [comment]
Why is this blocked?

**Comment by davidmiller** [comment]
Pending agreement with team ?

**Comment by michaeledwardmarks** [comment]
Yeah, it turned out to map pretty easily.I just added the ones we were missing. 
We can check this is correct with Sarah but I think this is done

**Comment by michaeledwardmarks** [comment]
Sarah Logan happy for this.
Unblocked.
Look-up list as per david-staging.
- [ ] Make Delivered by Mandatory on OPAT list when adding antimicrobial
- [ ] Set this field automatically to inpatient team for all lists in the background

**Comment by michaeledwardmarks** [comment]
@michaeledwarmarks to change the list in admin
@davidmiller to make it autopopulate with inpatient team for all drugs presribed by inpatient teams (e.g non-opat,non-walk-in patients)

**Comment by davidmiller** [comment]
@michaeledwardmarks The autopopulation is currently blocked by openhealthcare/opal#315

**Comment by michaeledwardmarks** [comment]
Lookup list bit done.
Remaining issues bumped to 0.5
