### ISSUE TITLE
Should OPAT outcomes modal be available to patients on the OPAT referral list?

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-opat#28]
I'd think not (they may not ever even be OPAT patients), but perhaps in short termas it's just a very finite number of users, and also can be edited down the line
@michaeledwardmarks @davidmiller

**Comment by michaeledwardmarks** [comment]
These outcomes are by definition (National Outcome Reporting System - NORS) collected on people at the end of the IV element of their OPAT care.
So I think the answer to this is no.

**Comment by michaeledwardmarks** [comment]
Closing based on our OPAT flow discussion today.
