### ISSUE TITLE
Look-up Lists for 0.4.3

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#32]
- [ ] Referring Team
- [ ] Primary Infective Diagnosis
- [ ] Adverse Events for Drugs
- [ ] Adverse Events for Lines
- [x] Dressing Type
  (CHG, Biopatch, Transparent)

**Comment by davidmiller** [comment]
We have to be careful changing or updating some of these so as to not lose old data on e.g. adverse events.
