### ISSUE TITLE
On Single Patient View (and therefore OPAT Ward-Rounds) we need to name the OPAT outcome headers better

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#33]
![opat outcome](https://cloud.githubusercontent.com/assets/4578105/10426970/5488a142-70dd-11e5-9a46-a9ddc6acb709.png)

Otherwise quite confusing!

So headings should be something like:

Outcome at end of IV:

Outcome at end of OPAT follow-up:

Outcome at final OPAT review:

**Comment by michaeledwardmarks** [comment]
As mentioned in OPAT Flow #12 this could also be reflected in the OPAT-Outcome-Stage in Admin for when we extract data and to allow us to separate outcomes at the different stages

**Comment by davidmiller** [comment]
Updated to indicate when it's post f/u

**Comment by michaeledwardmarks** [comment]
Can you stick IV in for the IV one?
and the post-follow-up one needs a space between Therapy and Post-Follow-Up
"Completed TherapyPost Follow Up"
(Just to make it really obvious)

**Comment by davidmiller** [comment]
I've added a space in between Therapy and post follow up.

The team were keen that we drop the IV vs Oral terminology though - they want OPAT Referral, OPAT treatment, OPAT follow up IIRC.

**Comment by michaeledwardmarks** [comment]
OK.

**Comment by davidmiller** [comment]
Deployed to david-staging

**Comment by michaeledwardmarks** [comment]
FAB
