### ISSUE TITLE
Item could not be saved error when adding referring team at the point of accepting on to OPAT

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#34]
NB If you ignore the warning, close the modal and then move to OPAT-Current the patient has been processed correctly.
![itemcouldnotbesaved](https://cloud.githubusercontent.com/assets/4578105/10427427/85157444-70e1-11e5-95b5-da4e47e3f3ec.png)

**Comment by michaeledwardmarks** [comment]
Still getting error message.

**Comment by davidmiller** [comment]
Deployed to david-staging

**Comment by michaeledwardmarks** [comment]
FIXED!
