### ISSUE TITLE
Stop counting line days after date removed

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-opat#38]
We keep missing this because we keep forgetting to make an issue.
Now we have an issue so we can fix it.

**Comment by davidmiller** [comment]
This looks fixed to me !

**Comment by davidmiller** [comment]
Sorry - missed this - what we're after is:
- Until we have a stopped date, days since line insertion
- After we have a stopped date, total days active

**Comment by fredkingham** [comment]
I think a nice to have would be for the filter to only show "day" rather than "days" if there is only one date but I think that's more a flag that can be passed or some moment tweaking

**Comment by GabPoll** [comment]
nice
