### ISSUE TITLE
Improve OPAT details screen usage

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-opat#5]
Reviewing the real world OPAT entries we would like to update the details page to move Outstanding issues above OPAT Review and then make OPAT Review a full width timeline entry to improve readability.

**Comment by davidmiller** [comment]
Fixed and deployed to http://david-staging.herokuapp.com/

**Comment by michaeledwardmarks** [comment]
Looks good.

**Comment by GabPoll** [comment]
looks nice BTW
