### ISSUE TITLE
As a User I would like a Ward Round of OPAT Current patients

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-opat#6]
So that we can move through them one by one in our MDT.

This requires a fix to openhealthcare/elcid#669 to be in place - without which the detail screen will be unusable!

**Comment by davidmiller** [comment]
Done and deployed to http://david-staging.herokuapp.com/

**Comment by michaeledwardmarks** [comment]
Perfect openhealthcare/elcid#669
