### ISSUE TITLE
Re-name OPAT flow buttons / growl messages

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-opat#7]
After reviewing the first six months of OPAT usage, we have realised that while a switch to oral is the most _common_ cause of moving a patient from Current -> Follow Up, there are other reasons. 

Accordingly, we'd like to re-name "Switch to oral" buttons and growl notifications to "move to follow up"

**Comment by michaeledwardmarks** [comment]
I believe this is correct now?
The option says: ongoing follow-up which I believe is in line with the above

**Comment by davidmiller** [comment]
Great - let's close it then :)
