### ISSUE TITLE
As a User I would like to see OPAT outcomes on the detail screen

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-opat#8]
Because the outcomes are important information in my care or review of this patient  !

**Comment by GabPoll** [comment]
and be able to retrospectively edit this (jn case clinical circumstance change or reporting authority changes reporting guidance).

**Comment by davidmiller** [comment]
Fixed and deployed to http://david-staging.herokuapp.com/

**Comment by michaeledwardmarks** [comment]
Correct!
Note that we have some new issues on how we collect these:
#20 
#10
